accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from accounts.forms.password.forms import UserPasswordResetForm
from accounts.views.group.views import (GroupCreateView, GroupDeleteView,
                                        GroupListView, GroupUpdateView)
from accounts.views.password.views import (AdminPasswordChangeView,
                                           PasswordChangeView, UserPasswordResetView)
from accounts.views.profile.views import ProfileDetailView, ProfileUpdateView
from accounts.views.user.views import (UserCreateView, UserDeleteView,
                                       UserListView, UserUpdateView)

urlpatterns = [
    # Grupos
    path('groups/', GroupListView.as_view(), name='groups'),
    path('group/create/', GroupCreateView.as_view(), name='create_group'),
    path('group/update/<uuid:uuid>/', GroupUpdateView.as_view(), name='update_group'),
    path('group/delete/<uuid:uuid>', GroupDeleteView.as_view(), name='delete_group'),
    # Usuarios
    path('users/', UserListView.as_view(), name='users'),
    path('user/create/', UserCreateView.as_view(), name='create_user'),
    path('user/update/<uuid:uuid>/', UserUpdateView.as_view(), name='update_user'),
    path('user/delete/<uuid:uuid>', UserDeleteView.as_view(), name='delete_user'),
    # Perfil
    path('user/profile/', ProfileDetailView.as_view(), name='profile'),
    path('user/profile/update/<uuid:uuid>/', ProfileUpdateView.as_view(), name='update_profile'),
    # Password
    path('user/password_change/', PasswordChangeView.as_view(), name='password_change'),
    path('user/password_change/<uuid:uuid>/', AdminPasswordChangeView.as_view(), name='admin_password_change'),
    # path('password_reset/', auth_views.PasswordResetView.as_view(template_name='pages/accounts/password/password_reset.html', form_class=UserPasswordResetForm), name='password_reset'),
    path('password_reset/', UserPasswordResetView.as_view(template_name='pages/accounts/password/password_reset.html', form_class=UserPasswordResetForm), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='pages/accounts/password/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='pages/accounts/password/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='pages/accounts/password/password_reset_complete.html'), name='password_reset_complete'),
]

api/urls.py
from django.urls import include, path
from drf_spectacular.views import (SpectacularAPIView, SpectacularRedocView,
                                   SpectacularSwaggerView)
from rest_framework.routers import DefaultRouter

from api.views import (ForecastAPIView, StationListAPIView,
                       StationObservationView)

router = DefaultRouter()

urlpatterns = router.urls + [
    # Autenticacion
    path('auth/', include('rest_framework.urls')),
    # Documentacion
    path('doc/', SpectacularSwaggerView.as_view(url_name='schema'), name='doc'),
    path('redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
    path('schema/', SpectacularAPIView.as_view(), name='schema'),
    # Estaciones
    path('stations/', StationListAPIView.as_view(), name='station-list'),
    path('station/observation/<str:hour>/<int:station_number>/', StationObservationView.as_view(), name='station-observation'),
    # Pronosticos
    path('forecast/<str:date>/', ForecastAPIView.as_view(), name='forecast'),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from common.utils import My400View, My403View, My404View, My500View, test_400, test_403, test_404, test_500


urlpatterns = [
    path('', include('login.urls')),
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('accounts/', include('accounts.urls')),
    path('dashboard/', include('dashboard.urls')),
    
    
    path('test-400/', test_400, name='test_400'),
    path('test-403/', test_403, name='test_403'),
    path('test-404/', test_404, name='test_404'),
    path('test-500/', test_500, name='test_500'),
    
    path('', include('home.urls')),
]

handler400 = My400View.as_view()
handler403 = My403View.as_view()
handler404 = My404View.as_view()
handler500 = My500View.as_view()

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/forms/password/forms.py
from django import forms
from datetime import datetime
from django.contrib.auth.forms import PasswordChangeForm, PasswordResetForm
from django.urls import reverse
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError


class UserPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(
        label='Contraseña Actual',
        widget=forms.PasswordInput(attrs={'class': 'form-control'})
    )
    new_password1 = forms.CharField(
        label='Nueva Contraseña',
        widget=forms.PasswordInput(attrs={'class': 'form-control'})
    )
    new_password2 = forms.CharField(
        label='Confirmar Nueva Contraseña',
        widget=forms.PasswordInput(attrs={'class': 'form-control'})
    )

class AdminPasswordChangeForm(forms.ModelForm):
    new_password1 = forms.CharField(label='Nueva contraseña', widget=forms.PasswordInput)
    new_password2 = forms.CharField(label='Confirmar nueva contraseña', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = []

    def clean(self):
        cleaned_data = super().clean()
        new_password1 = cleaned_data.get("new_password1")
        new_password2 = cleaned_data.get("new_password2")

        if new_password1 and new_password2 and new_password1 != new_password2:
            raise forms.ValidationError("Las contraseñas no coinciden.")

        return cleaned_data

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["new_password1"])
        if commit:
            user.save()
        return user

class UserPasswordResetForm(PasswordResetForm):
    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)  # Extraer la solicitud del formulario
        super().__init__(*args, **kwargs)

    def send_mail(self, subject_template_name, email_template_name, context, from_email, to_email, html_email_template_name=None):
        # Construir la URL completa al índice
        index_url = self.request.build_absolute_uri(reverse('index'))
        context['index_url'] = index_url  # Pasar la URL al contexto del correo

        # Construir la URL completa para el enlace de restablecimiento
        reset_url = self.request.build_absolute_uri(
            reverse('password_reset_confirm', kwargs={
                'uidb64': context['uid'],  # UID codificado
                'token': context['token'],  # Token generado
            })
        )
        context['reset_url'] = reset_url  # Pasar la URL al contexto del correo

        # Agregar el año actual al contexto
        context['current_year'] = datetime.now().year

        # Llamar al método base para enviar el correo
        html_email_template_name = 'pages/accounts/emails/password_reset_email.html'  # Template HTML personalizado
        super().send_mail(subject_template_name, email_template_name, context, from_email, to_email, html_email_template_name)

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if not User.objects.filter(email=email).exists():
            raise ValidationError("La dirección de correo electrónico no es valida.")
        return email

accounts/views/group/views.py
from django.contrib import messages
from django.contrib.auth.mixins import (LoginRequiredMixin,
                                        PermissionRequiredMixin,
                                        UserPassesTestMixin)
from django.contrib.auth.models import Group
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

from accounts.forms.group.form import GroupForm
from accounts.models import GroupProfile

from django.contrib.admin.models import ADDITION, CHANGE, DELETION

from common.utils import log_action

# Create your views here.

class GroupListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    template_name = 'pages/accounts/groups/groups.html'
    permission_required = 'auth.view_group'
    model = Group

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Listado de Grupos'
        context['parent'] = 'accounts'
        context['segment'] = 'groups'
        context['btn'] = ('Añadir Grupo')
        context['url_create'] = reverse_lazy('create_group')
        context['url_list'] = reverse_lazy('groups')
        context['objects'] = Group.objects.all()

        return context
    
class GroupCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Group
    form_class = GroupForm
    template_name = 'pages/accounts/groups/group_create.html'
    permission_required = 'auth.add_group'
    success_url = reverse_lazy('groups')
    url_redirect = success_url

    def form_valid(self, form):
        group = form.save()
        group_profile, created = GroupProfile.objects.get_or_create(group=group)
        
        # Registro de acción
        log_action(
            user=self.request.user,
            obj=group,
            action_flag=ADDITION,
            message=f"Se creó un nuevo grupo {group.name}."
        )
        
        messages.success(self.request, 'El grupo ha sido creado con éxito.', extra_tags='success')
        return redirect('groups')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Añadir Grupos'
        context['parent'] = 'accounts'
        context['segment'] = 'groups'
        context['url_list'] = self.success_url
        return context

class GroupUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Group
    form_class = GroupForm
    template_name = 'pages/accounts/groups/group_update.html'
    permission_required = 'auth.change_group'
    success_url = reverse_lazy('groups')

    def get_object(self):
        uuid = self.kwargs.get('uuid')
        group_profile = get_object_or_404(GroupProfile, uuid=uuid)
        return group_profile.group

    def form_valid(self, form):
        response = super().form_valid(form)
        
        # Registro de acción
        log_action(
            user=self.request.user,
            obj=self.object,
            action_flag=CHANGE,
            message=f"Se actualizó el grupo {self.object.name}."
        )
        
        messages.success(self.request, 'El grupo ha sido actualizado con éxito.', extra_tags='warning')
        return response

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Actualizar Grupo'
        context['parent'] = 'accounts'
        context['segment'] = 'groups'
        context['url_list'] = self.success_url
        return context

    def test_func(self):
        return self.request.user.is_superuser or self.get_object().user == self.request.user

class GroupDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Group
    template_name = 'pages/accounts/groups/group_delete.html'
    permission_required = 'auth.delete_group'
    success_url = reverse_lazy('groups')

    def get_object(self):
        uuid = self.kwargs.get('uuid')
        group_profile = get_object_or_404(GroupProfile, uuid=uuid)
        return group_profile.group

    def post(self, request, *args, **kwargs):
        group = self.get_object()
        
        # Registro de acción antes de eliminar el grupo
        log_action(
            user=self.request.user,
            obj=group,
            action_flag=DELETION,
            message=f"Se eliminó el grupo {group.name}."
        )
        
        try:
            group.delete()
            messages.success(request, 'El grupo ha sido eliminado con éxito.', extra_tags='danger')
        except Exception as e:
            messages.error(request, str(e))
        return redirect(self.success_url)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Eliminar Grupo'
        context['parent'] = 'accounts'
        context['segment'] = 'groups'
        context['url_list'] = reverse_lazy('groups')
        return context

accounts/views/password/views.py
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.mixins import (LoginRequiredMixin,
                                        PermissionRequiredMixin)
from django.contrib.auth.views import PasswordResetView
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic.edit import FormView

from accounts.forms.password.forms import (AdminPasswordChangeForm,
                                           UserPasswordChangeForm)

from django.contrib.admin.models import CHANGE
from common.utils import log_action


# Create your views here.

class PasswordChangeView(LoginRequiredMixin, FormView):
    template_name = 'pages/accounts/password/password_change.html'
    form_class = UserPasswordChangeForm
    success_url = reverse_lazy('profile')
    url_redirect = success_url

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user  # Pasar el usuario autenticado al formulario
        return kwargs

    def form_valid(self, form):
        user = form.save()
        update_session_auth_hash(self.request, user)  # Mantener la sesión del usuario después de cambiar la contraseña
        
        # Registro de la acción
        log_action(
            user=self.request.user,
            obj=user,
            action_flag=CHANGE,
            message="El usuario cambió su contraseña."
        )
        
        messages.success(self.request, 'Tu contraseña ha sido cambiada con éxito.')
        return super().form_valid(form)
    
    def get_context_data(self, **kwargs): 
        context = super().get_context_data(**kwargs) 
        context['title'] = 'Cambiar Contraseña' 
        context['parent'] = 'accounts' 
        context['segment'] = 'password_change' 
        context['url_list'] = self.success_url
        return context

class AdminPasswordChangeView(LoginRequiredMixin, PermissionRequiredMixin, FormView):
    template_name = 'pages/accounts/password/admin_password_change.html'
    form_class = AdminPasswordChangeForm
    permission_required = 'auth.change_user'
    success_url = reverse_lazy('users')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        user = get_object_or_404(User, profile__uuid=self.kwargs.get('uuid'))
        kwargs['instance'] = user  # Pasar el usuario a editar al formulario
        return kwargs

    def form_valid(self, form):
        user = form.save()
        
        # Registro de la acción
        log_action(
            user=self.request.user,
            obj=user,
            action_flag=CHANGE,
            message=f"El administrador {self.request.user.username} cambió la contraseña del usuario {user.username}."
        )
        
        messages.success(self.request, 'La contraseña del usuario ha sido cambiada con éxito.')
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Cambiar Contraseña del Usuario'
        context['parent'] = 'accounts'
        context['segment'] = 'password_change'
        context['url_list'] = self.success_url
        return context

class UserPasswordResetView(PasswordResetView):
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['request'] = self.request  # Pasar la solicitud al formulario
        return kwargs

templates/pages/accounts/password/admin_password_change.html
{% extends 'layouts/form.html' %}

{% block form %}
  <div class="mb-3">
    <label class="form-label required" for="id_new_password1">Nueva contraseña</label>
    <input type="password" class="form-control" id="id_new_password1" name="new_password1" required>
    {% if form.new_password1.errors %}
      <span class="text-danger d-block mb-3">{{ form.new_password1.errors }}</span>
    {% endif %}
  </div>
  <div class="mb-3">
    <label class="form-label required" for="id_new_password2">Confirmar nueva contraseña</label>
    <input type="password" class="form-control" id="id_new_password2" name="new_password2" required>
    {% if form.new_password2.errors %}
      <span class="text-danger d-block mb-3">{{ form.new_password2.errors }}</span>
    {% endif %}
  </div>
{% endblock form %}

templates/pages/accounts/password/password_change.html
{% extends 'layouts/form.html' %}
{% load static %}
{% block form %}
<div class="mb-3">
  <label class="form-label required">{{ form.old_password.label }}</label>
  <input type="password" class="form-control" id="{{ form.old_password.id_for_label }}" name="{{ form.old_password.name }}" required>
  {% if form.old_password.errors %}
    <span class="text-danger d-block mb-3">{{ form.old_password.errors }}</span>
  {% endif %}
</div>
<div class="mb-3">
  <label class="form-label required">{{ form.new_password1.label }}</label>
  <input type="password" class="form-control" id="{{ form.new_password1.id_for_label }}" name="{{ form.new_password1.name }}" required>
  {% if form.new_password1.errors %}
    <span class="text-danger d-block mb-3">{{ form.new_password1.errors }}</span>
  {% endif %}
</div>
<div class="mb-3">
  <label class="form-label required">{{ form.new_password2.label }}</label>
  <input type="password" class="form-control" id="{{ form.new_password2.id_for_label }}" name="{{ form.new_password2.name }}" required>
  {% if form.new_password2.errors %}
    <span class="text-danger d-block mb-3">{{ form.new_password2.errors }}</span>
  {% endif %}
</div>
{% endblock form %}

templates/pages/accounts/password/password_reset.html
{% extends 'layouts/base-auth.html' %}
{% load static %}
{% block content %}
<div class="page page-center">
  <div class="container container-tight py-4">
    <div class="text-center mb-4">
      <img src="{% static '' %}dist/img/webp/bad-news.webp" alt="boy-with-key">
    </div>
    <div class="card card-md">
      <div class="card-body">
        <h2 class="card-title text-center mb-4">Olvidé mi contraseña</h2>
        <p class="text-secondary mb-4">Ingrese su dirección de correo y se le enviarán las instrucciones para restablecer su contraseña.</p>
        <form method="post">
          {% csrf_token %}
          {% if form.non_field_errors %}
            {% for error in form.non_field_errors %}
              <span class="text-danger d-block mb-3">{{ error }}</span>
            {% endfor %}
          {% endif %}
          <div class="mb-3">
            <!-- <label class="form-label">{{ form.email.label }}</label> -->
              <input type="email" class="form-control" id="{{ form.email.id_for_label }}" name="{{ form.email.name }}" placeholder="Correo Electrónico" autofocus>
              {% if form.email.errors %}
                  <span class="text-danger d-block mb-3">{{ form.email.errors }}</span>
              {% endif %}
          </div>
          <div class="form-footer">
            <button type="submit" class="btn btn-primary w-100">
              <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M3 7a2 2 0 0 1 2 -2h14a2 2 0 0 1 2 2v10a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-10z" /><path d="M3 7l9 6l9 -6" /></svg>
              Restablecer Contraseña
            </button>
          </div>
        </form>
      </div>
    </div>
    <div class="text-center text-secondary mt-3">
      Olvídalo, <a href="{% url 'login' %}">envíame de vuelta</a> a la pantalla de inicio de sesión.
    </div>
  </div>
</div>
{% endblock %}

templates/pages/accounts/password/password_reset_complete.html
{% extends 'layouts/base-auth.html' %}
{% load static %}
{% block content %}
<div class="page page-center">
  <div class="container-xl">
    <div class="empty">
      <img src="{% static '' %}dist/img/webp/good-news.webp" alt="good-news">
        <p class="empty-title">Contraseña Restablecida</p>
        <p class="empty-subtitle text-secondary">
          Tu contraseña ha sido restablecida con éxito. Ahora puedes <a href="{% url 'login' %}">iniciar sesión</a> con tu nueva contraseña.
        </p>
    </div>
  </div>
</div>
{% endblock %}

templates/pages/accounts/password/password_reset_confirm.html
{% extends 'layouts/base-auth.html' %}
{% load static %}
{% block content %}
<div class="page page-center">
  <div class="container container-tight py-4">
    <div class="text-center mb-4">
      <img src="{% static '' %}dist/img/webp/boy-with-key.webp" alt="boy-with-key">
    </div>
    <div class="card card-md">
      <div class="card-body">
        <h2 class="card-title text-center mb-4">Establecer Nueva Contraseña</h2>
        <form method="post">
          {% csrf_token %}
          {% if form.non_field_errors %}
            {% for error in form.non_field_errors %}
              <span class="text-danger d-block mb-3">{{ error }}</span>
            {% endfor %}
          {% endif %}
          <div class="mb-3">
            <label class="form-label">{{ form.new_password1.label }}</label>
              <input type="password" class="form-control" id="{{ form.new_password1.id_for_label }}"
                      name="{{ form.new_password1.name }}" placeholder="Nueva Contraseña" autofocus>
              {% if form.new_password1.errors %}
                  <span class="text-danger d-block mb-3">{{ form.new_password1.errors }}</span>
              {% endif %}
          </div>
          <div class="mb-3">
            <label class="form-label">{{ form.new_password2.label }}</label>
              <input type="password" class="form-control" id="{{ form.new_password2.id_for_label }}"
                      name="{{ form.new_password2.name }}" placeholder="Confirmar Nueva Contraseña">
              {% if form.new_password2.errors %}
                  <span class="text-danger d-block mb-3">{{ form.new_password2.errors }}</span>
              {% endif %}
          </div>
          <div class="form-footer">
            <button type="submit" class="btn btn-primary w-100">Restablecer Contraseña</button>
          </div>
        </form>
      </div>
    </div>
    <div class="text-center text-secondary mt-3">
      Olvídalo, <a href="{% url 'login' %}">envíame de vuelta</a> a la pantalla de inicio de sesión.
    </div>
  </div>
</div>
{% endblock %}

templates/pages/accounts/password/password_reset_done.html
{% extends 'layouts/base-auth.html' %}
{% load static %}
{% block content %}
<div class="page page-center">
  <div class="container-xl">
    <div class="empty">
      <img src="{% static 'dist/img/webp/email.webp' %}" class="mode-image" alt="email">
        <p class="empty-title">Correo Enviado</p>
        <p class="empty-subtitle text-secondary">
          Hemos enviado un correo electrónico con las instrucciones para restablecer tu contraseña.
        </p>
    </div>
  </div>
</div>
{% endblock %}